title: "Technical Support Portfolio"
description: "Portfolio of Faizah Shaikh, Technical Support Engineer specializing in ETL workflows, database management, and troubleshooting."
theme: minima
baseurl: "/technical-support-portfolio"
url: "https://faizah-tech.github.io"
author:
  name: "Faizah Shaikh"
  email: "faizahmushtaaq@gmail.com"
  linkedin: "https://www.linkedin.com/in/faizah-shaikh-88a1ba146/"
  github: "https://github.com/Faizah-Tech"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
