title: Faizah Shaikh - Technical Support Portfolio
description: A portfolio showcasing expertise in troubleshooting, database management, ETL testing, and data visualization.
baseurl: "/technical-support-portfolio" # Repository name
url: "https://faizah-tech.github.io" # Base URL
author: Faizah Shaikh
email: your.email@example.com
github: https://github.com/Faizah-Tech/technical-support-portfolio
linkedin: https://www.linkedin.com/in/faizah-shaikh-88a1ba146/

# Theme settings
theme: minima

# Navigation
nav_links:
  - name: Home
    url: "/"
  - name: Projects
    url: "/projects/"
  - name: Contact
    url: "/#contact"

# Social links
social_links:
  github: https://github.com/Faizah-Tech
  linkedin: https://www.linkedin.com/in/faizah-shaikh-88a1ba146/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
